language: bash

services:
  - docker

before_install:
  - sudo apt-get install -y postgresql-client shunit2
  - docker pull postgres:11

script:
    - docker run -d -p 5432:5432 postgres
    - sleep 5
    - cd tests
    - ./test.sh
