language: bash

services:
  - docker

before_install:
  - sudo apt-get install -y postgresql-client shunit2
  - docker pull postgres:latest

script:
  - docker run -d -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust postgres:latest
  - sleep 5
  - cd tests
  - ./test.sh
